function out = dFdeps(Xp,mi,p)
%DFDEPS Summary of this function goes here
%   Detailed explanation goes here

xp = Xp(1);
yp = Xp(2);
psip = Xp(3);

x_c = p(1);
y_c = p(2);
phi = p(3);
a = p(4);
b = p(5);
epsilon = p(6);

di = mi(:,1);
thetai = mi(:,2);

x = xp+di.*cos(thetai+psip);
y = yp + di.*sin(thetai+psip);
out = a^(1/2)*b^(1/2)*(log((abs(cos(phi)*(x - x_c) +...
    sin(phi)*(y - y_c))/a).^(2/epsilon) +...
    (abs(cos(phi)*(y - y_c) -...
    sin(phi)*(x - x_c))/b).^(2/epsilon)).*((abs(cos(phi)*(x - x_c) +...
    sin(phi)*(y - y_c))/a).^(2/epsilon) + (abs(cos(phi)*(y - y_c) -...
    sin(phi)*(x - x_c))/b).^(2/epsilon)).^epsilon -...
    epsilon*((2*log(abs(cos(phi)*(x - x_c) + ...
    sin(phi)*(y - y_c))/a).*(abs(cos(phi)*(x - x_c) + ...
    sin(phi)*(y - y_c))/a).^(2/epsilon))/epsilon^2 + ...
    (2*log(abs(cos(phi)*(y - y_c) - ...
    sin(phi)*(x - x_c))/b).*(abs(cos(phi)*(y - y_c) - ...
    sin(phi)*(x - x_c))/b).^(2/epsilon))/epsilon^2).*((abs(cos(phi)*(x - x_c) + ...
    sin(phi)*(y - y_c))/a).^(2/epsilon) + (abs(cos(phi)*(y - y_c) - ...
    sin(phi)*(x - x_c))/b).^(2/epsilon)).^(epsilon - 1));
out = real(out)/sqrt(a*b);
end

